server:
  port: 8083

spring:
  application:
    name: tracking-service
  datasource:
    url: jdbc:mysql://localhost:3306/tracking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Sai@2003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Uploaded documents storage path
file:
  upload-dir: ./uploads/documents


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



logging:
  level:
    com.smartcourier.tracking: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction: TRACE


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  swagger-ui.tryItOutEnabled: true